# Generated by Django 4.1.3 on 2023-01-22 19:20

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='vid',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
