# Generated by Django 4.1.3 on 2023-01-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfs',
            old_name='file',
            new_name='pdf_file',
        ),
    ]
